### PR TITLE
Whiptail

### PR DESCRIPTION
**Pull request by zindy**
Interactive mode with `sudo ./setup.sh --interactive=true` (the default) or non-interactive with `sudo ./setup.sh --interactive=false`

All the default variables for non-interactive mode are defined in setup.sh.

The interactive mode uses whiptail (default on Debian based distributions). I will make sure that whiptail is also available on all the Red Hat based distros we support.

Other than that, I caught a few problems since Friday, most severe being some syntax errors in the HRM folder creation, which I missed because the folder was already created. Also the package installation for Debian based systems now also uses whiptail to make it consistent with the rest of the script.

I still need to look at (I'll add any that I forgot):
- Scripts:
  - [x] PostgreSQL
  - [x] Red Hat based systems (CentOS, Fedora)
- Testing
  - [ ] Ubuntu 18.0.4.1 (php7.2.10-0ubuntu0.18.04.1)
    - [x] Interactive mode
    - [x] Non-Interactive mode
  - [ ] Debian 8 (php5)
    - [x] Interactive mode
    - [x] Non-Interactive mode
  - [ ] Debian 9 (php7)
    - [x] Interactive mode
    - [x] Non-Interactive mode
  - [ ] CentOS 7 (php 5.6)
    - [x] Interactive mode
    - [x] Non-Interactive mode
  - [ ] Fedora 29 (php 7.2.12)
    - [x] Interactive mode
    - [x] Non-Interactive mode

Sorry about the massive commit in this branch!!

### CODE REVIEW

**Comment by zindy** [comment]
Just an update to mention I fixed a lot of warts in the code to try and streamline the installation as much as possible (especially in interactive mode).

I will test this again with a clean slate, but "master" now also seems to install just fine on Debian 9 (with auto detection of PHP7 in the script):

> Apache version	2.4.25
> Database type and version	mysqli 10.1.26
> PHP (Apache mod) version	7.0.30-0+deb9u1

The command I used:
`./setup.sh --interactive=false --hrmrepo="https://github.com/zindy/hrm.git" --hrmtag="master" --bypass=true --adminpass="booboo"`

My fork of hrm (for master) points composer.json to a usable repository of php-traditional-server (my own) and interestingly, I had to force an update in [setup/setup_release.sh](https://github.com/zindy/hrm/commit/9ef63c95fa7df2fa1f228283d2fbc47358a2fc81) for composer to install everything without issue.

**Comment by zindy** [comment]
As far as I can tell, everything in the install should work. I've tested the following combinations:
* interactive / non-interactive mode,
* tested with ubuntu / debian / centos / fedora.
* installation of php5 / php7 using code from Torsten and Felix
* systemd / sysv
* tested with mysql / postgresql,
* hrm from git or zip,

You're welcome to double check the combos. Also a lot of TODOs / FIXMEs left in the code, which probably could do with a second pair of eyes and some extra testing.

Next I'll update the documentation with some screenshots.

**Comment by zindy** [comment]
At this point, the installation script was tested on Debian 9 and will install HRM 3.6 with the defaults.

Installing the devel branch was tested on Ubuntu some time ago and should still work. Not sure about devel on any of the other platform we support.

Any reports of failure or success welcome!

---
**Edit**

Now that I have finished installing HRM 3.6 on a fresh Debian 9 system. I think there are still a few things  the install script could do better.

For instance, the Apache config file /etc/apache2/sites-available/000-default.cfg still needs editing by hand.

You will want to add the following lines [as per instructions](https://huygens-remote-manager.readthedocs.io/en/latest/admin/prerequisites.html#apache2-web-server):
```
        <Directory /var/www/hrm>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>
```

and possibly change the DocumentRoot:
```
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/hrm
```

In my case, because I have HRM and Hucore are on different servers (I *really* like the idea of not messing with hucore if it works), I had to run ssh-keygen on the HRM machine, both for the $hrmuser and root. Could be useful to do that from the installation script and present the pubkeys in a window. Then ask the user to copy paste the keys to authorized_keys on the hucore machine.

All in all, it was definitely quicker this time round with the install script, but then working out what was missing from my install did take a long time.

Watch this space for some new commits!

**Comment by aarpon** [comment]
The work on the whiptail branch has continued past this merge request. A proper merge will be done directly from the whiptail branch.

**Pull request closed without merging**
